// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandosAPI.Models;

#nullable disable

namespace PandosAPI.Migrations
{
    [DbContext(typeof(proteindomainannotationsContext))]
    [Migration("20220404025743_current-data-to-maria-db-1")]
    partial class currentdatatomariadb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.Property<string>("PdbId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pdb_id");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("uniprot_id");

                    b.HasKey("PdbId");

                    b.HasIndex("UniprotId");

                    b.ToTable("pdb");
                });

            modelBuilder.Entity("PandosAPI.Models.PdbChain", b =>
                {
                    b.Property<string>("PdbId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pdb_id");

                    b.Property<string>("PdbChainId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pdb_chain_id");

                    b.Property<string>("CytoplasmicDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cytoplasmic_domain");

                    b.Property<string>("HeadDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("head_domain");

                    b.Property<string>("HingeDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("hinge_domain");

                    b.Property<string>("NeckDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("neck_domain");

                    b.Property<string>("PdbSequence")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("pdb_sequence");

                    b.Property<string>("StalkDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stalk_domain");

                    b.Property<string>("TransmembraneDomain")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transmembrane_domain");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("uniprot_id");

                    b.HasKey("PdbId", "PdbChainId");

                    b.HasIndex("UniprotId");

                    b.ToTable("pdb_chain");
                });

            modelBuilder.Entity("PandosAPI.Models.Uniprot", b =>
                {
                    b.Property<string>("UniprotId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("uniprot_id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("accession_number");

                    b.Property<string>("EntryStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entry_status");

                    b.Property<string>("Sequence")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("sequence");

                    b.HasKey("UniprotId");

                    b.ToTable("uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.HasOne("PandosAPI.Models.Uniprot", "Uniprot")
                        .WithMany("Pdbs")
                        .HasForeignKey("UniprotId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_uniprot");

                    b.Navigation("Uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.PdbChain", b =>
                {
                    b.HasOne("PandosAPI.Models.Pdb", "Pdb")
                        .WithMany("PdbChains")
                        .HasForeignKey("PdbId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_chain_pdb");

                    b.HasOne("PandosAPI.Models.Uniprot", "Uniprot")
                        .WithMany("PdbChains")
                        .HasForeignKey("UniprotId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_chain_uniprot");

                    b.Navigation("Pdb");

                    b.Navigation("Uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.Navigation("PdbChains");
                });

            modelBuilder.Entity("PandosAPI.Models.Uniprot", b =>
                {
                    b.Navigation("PdbChains");

                    b.Navigation("Pdbs");
                });
#pragma warning restore 612, 618
        }
    }
}
