// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandosAPI.Models;

#nullable disable

namespace PandosAPI.Migrations
{
    [DbContext(typeof(pandosdbContext))]
    partial class pandosdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("MySql:CharSet", "utf8mb4")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PandosAPI.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory");
                });

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.Property<string>("PdbId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pdb_id");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uniprot_id");

                    b.HasKey("PdbId");

                    b.HasIndex(new[] { "UniprotId" }, "IX_pdb_uniprot_id");

                    b.ToTable("pdb");
                });

            modelBuilder.Entity("PandosAPI.Models.PdbChain", b =>
                {
                    b.Property<string>("PdbId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("pdb_id");

                    b.Property<string>("PdbChainId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("pdb_chain_id");

                    b.Property<string>("CytoplasmicDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cytoplasmic_domain");

                    b.Property<string>("HeadDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("head_domain");

                    b.Property<string>("HingeDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("hinge_domain");

                    b.Property<string>("NeckDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("neck_domain");

                    b.Property<string>("PdbSequence")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pdb_sequence");

                    b.Property<string>("StalkDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("stalk_domain");

                    b.Property<string>("TransmembraneDomain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("transmembrane_domain");

                    b.Property<string>("UniprotId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uniprot_id");

                    b.HasKey("PdbId", "PdbChainId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "UniprotId" }, "IX_pdb_chain_uniprot_id");

                    b.ToTable("pdb_chain");
                });

            modelBuilder.Entity("PandosAPI.Models.Uniprot", b =>
                {
                    b.Property<string>("UniprotId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("uniprot_id");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("accession_number");

                    b.Property<string>("EntryStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entry_status");

                    b.Property<string>("Sequence")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("sequence");

                    b.HasKey("UniprotId");

                    b.ToTable("uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.HasOne("PandosAPI.Models.Uniprot", "Uniprot")
                        .WithMany("Pdbs")
                        .HasForeignKey("UniprotId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_uniprot");

                    b.Navigation("Uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.PdbChain", b =>
                {
                    b.HasOne("PandosAPI.Models.Pdb", "Pdb")
                        .WithMany("PdbChains")
                        .HasForeignKey("PdbId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_chain_pdb");

                    b.HasOne("PandosAPI.Models.Uniprot", "Uniprot")
                        .WithMany("PdbChains")
                        .HasForeignKey("UniprotId")
                        .IsRequired()
                        .HasConstraintName("FK_pdb_chain_uniprot");

                    b.Navigation("Pdb");

                    b.Navigation("Uniprot");
                });

            modelBuilder.Entity("PandosAPI.Models.Pdb", b =>
                {
                    b.Navigation("PdbChains");
                });

            modelBuilder.Entity("PandosAPI.Models.Uniprot", b =>
                {
                    b.Navigation("PdbChains");

                    b.Navigation("Pdbs");
                });
#pragma warning restore 612, 618
        }
    }
}
